services:
  app:
    container_name: app
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "7995:8000"
    volumes:
      - ./app:/app
      - ./data/web/static:/data/web/static
      - ./data/web/media:/data/web/media
    env_file:
      - ./dotenv_files/.env

    depends_on:
      - psql

  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
